project:
  type: website

website:
  title: "What Will We Eat?"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: journal.qmd
        text: Details
      - href: random_pick.qmd
        text: Help Me!
      - about.qmd

format:
  html:
    theme: cosmo
    css: style.css
    toc: true

editor: visual

