project:
  type: website

website:
  title: "What Will We Eat?"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: journal.qmd
        text: Gallery
      - href: random_pick.qmd
        text: Help Me!
      - href: about.qmd
        text: About

format:
  html:
    theme: lux
    css: style.css
    toc: true

editor: visual

